LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := lz4

LOCAL_C_INCLUDES := $(LOCAL_PATH)/lz4/lib

LOCAL_SRC_FILES := $(wildcard $(LOCAL_PATH)/lz4/lib/*.c)

LOCAL_EXPORT_C_INCLUDES += $(LOCAL_C_INCLUDES)

include $(BUILD_SHARED_LIBRARY)
