add_library(sosage INTERFACE IMPORTED)
set_target_properties(sosage PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SOSAGE_DATA_FOLDER=\"${SOSAGE_DATA_FOLDER}/data/\";SOSAGE_LINKED_WITH_SDL_MIXER"
  INTERFACE_INCLUDE_DIRECTORIES   "${CMAKE_SOURCE_DIR}/include;${YAML_INCLUDE_DIR};${SDL2_INCLUDE_DIR};${SDL2_IMAGE_INCLUDE_DIR};${SDL2_TTF_INCLUDE_DIR};${SDL2_MIXER_INCLUDE_DIR}"
  INTERFACE_LINK_LIBRARIES "${YAML_LIBRARIES};${SDL2_LIBRARY};${SDL2_IMAGE_LIBRARIES};${SDL2_TTF_LIBRARIES};${SDL2_MIXER_LIBRARIES}")

function(sosage_add_test target)
  add_test(NAME "compiling_${target}" COMMAND "${CMAKE_COMMAND}" --build "${CMAKE_BINARY_DIR}" --target "${target}")
  add_test(NAME "running_${target}" COMMAND "${target}")
endfunction()
